sudo: required
services:
    - docker
    
before_install:
    - docker build -t difalcomarco/docker-react -f Dockerfile.dev .

script:
    - docker run difalcomarco/docker-react npm run test -- --coverage