version: '3'
services:
    web:
        build: 
            context: .
            dockerfile: Dockerfile.dev 
        ports:
            - "3000:3000"
        volumes:
            - C:\Users\marco.difalco\Desktop\docker\frontend\node_modules
            - .:/app 
    tests:
        build: 
            context: . 
            dockerfile: Dockerfile.dev 
        volumes:
            - C:"\Users"\marco.difalco"\Desktop"\docker"\frontend"\node_modules
            - .:/app
        command: ["npm", "run" , "test"]